### ISSUE TITLE
你建立数据表报错

### ISSUE THREAD

**Issue by sfreesOK** [Ehco1996/django-sspanel#112]
root@vultr django-sspanel]# python manage.py migrate

Traceback (most recent call last):

  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()

  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  
File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 236, in get_new_connection
    return Database.connect(**conn_params)
  
File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/MySQLdb/__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)

  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: NO)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)

  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
 
 File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  
File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/base.py", line 332, in execute
    self.check()
  
File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,

  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 57, in _run_checks
    issues = run_checks(tags=[Tags.database])

  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)

  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/checks/database.py", line 10, in check_database_backends
    issues.extend(conn.validation.check(**kwargs))
 
 File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/mysql/validation.py", line 9, in check
    issues.extend(self._check_sql_mode(**kwargs))

  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/mysql/validation.py", line 13, in _check_sql_mode
    with self.connection.cursor() as cursor:

  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()

  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
    self.ensure_connection()

  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
 
 File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
 
 File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)

  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 236, in get_new_connection
    return Database.connect(**conn_params)

  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/MySQLdb/__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)

  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: NO)")

**Comment by Ehco1996** [comment]
这不就是密码不对么，或者权限没打开么。。。。

**Comment by sfreesOK** [comment]
我确认过了  数据库密码对的   权限也打开了

**Comment by Ehco1996** [comment]
@sfreesOK @moonmilker 

是配置文件被覆盖了，是个bug
我刚更新了一个版本， 已经修复了， 直接在db.py里设置就行了

**Comment by moonmilker** [comment]
已经解决

**Comment by sfreesOK** [comment]
感谢

**Comment by cyang812** [comment]
请问 db.py 里面的 host 项怎么填？

**Comment by cyang812** [comment]
我用的应该是新版本，还是一样的问题。是我 db.py 里面配置有问题吗
