### ISSUE TITLE
大佬又来麻烦你了

### ISSUE THREAD

**Issue by moonmilker** [Ehco1996/django-sspanel#116]
节点服务器连接不上网站数据库   刚开始报错是这个  
2018-05-07 02:11:08 ERROR    db_transfer.py:293 Traceback (most recent call last):
  File "/root/shadowsocksr/transfer/db_transfer.py", line 275, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocksr/transfer/db_transfer.py", line 466, in pull_db_all_user
    db=self.cfg["db"], charset='utf8')
  File "/root/shadowsocksr/cymysql/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/root/shadowsocksr/cymysql/connections.py", line 245, in __init__
    self._connect()
  File "/root/shadowsocksr/cymysql/connections.py", line 413, in _connect
    self._request_authentication()
  File "/root/shadowsocksr/cymysql/connections.py", line 497, in _request_authentication
    auth_packet = self.read_packet()
  File "/root/shadowsocksr/cymysql/connections.py", line 418, in read_packet
    return MysqlPacket(self)
  File "/root/shadowsocksr/cymysql/packet.py", line 65, in __init__
    raise_mysql_exception(self.__data)
  File "/root/shadowsocksr/cymysql/err.py", line 149, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/root/shadowsocksr/cymysql/err.py", line 144, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (1043, u'Bad handshake')
=====================
很多次以后就被数据库服务block了
InternalError: (1129, u"Host '107.173.16.84' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'")
=================
宝塔的mysql只有一条记录
180507 13:20:31 [Warning] IP address '107.1.1.4' could not be resolved: Name or service not known
=====================
phpmyadmin的权限都开启了  确认多次了 用普通用户和root都连不上  两边服务器都没有防火墙

**Comment by moonmilker** [comment]
我在宝塔里面设置了 指定我的107.173 这个IP访问 权限也都是开的 任意主机访问   也在宝塔设置了t跳过解析了 还是t同样的错误

**Comment by Chennhaoo** [comment]
@moonmilker  看看宝塔开3306端口没，后端可以重新装一下cymysql，我用的是0.9.4版。
我怀疑是cymysql的问题

**Comment by Ehco1996** [comment]
最好不要直连数据库
