### ISSUE TITLE
webapi报错

### ISSUE THREAD

**Issue by moonmilker** [Ehco1996/django-sspanel#117]
2018-05-07 23:39:29 ERROR    web_tools.py:36 接口返回值不正确:{"ret": -1}
2018-05-07 23:39:29 ERROR    web_tools.py:37 请求头：/nodes/2
2018-05-07 23:39:29 WARNING  web_transfer.py:264 没有查询到满足要求的节点，请检查自己的node_id!,或者该节点流量已经用光,当前节点ID:2
=========

**Comment by moonmilker** [comment]
网站日志报错
2018/05/08 14:26:50 [error] 890#0: *10121 open() "/www/wwwroot/django-sspanel/pub/css/new_font.css" failed (2: No such file or directory), client: 182.92.107.227, server: 1688ss.xyz, request: "GET http://www.baidu.com/pub/css/new_font.css HTTP/1.1", host: "www.baidu.com"
====================
2018/05/08 11:39:02 [error] 890#0: *9904 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 163.172.72.31, server: 1688ss.xyz, request: "GET http://163.172.72.31:8081/service/echo HTTP/1.1", upstream: "uwsgi://127.0.0.1:8080", host: "163.172.72.31:8081"

**Comment by Ehco1996** [comment]
你ss后端配置那有问题

**Comment by moonmilker** [comment]
数据库的记录
id:1
node_id:333
total_traffic:100G
无论是1还是333都是包上面的错误   数据库有记录设置了节点100G流量
我是不是用错版本了 dev   master   
我直接复制的节点部署的下载链接

**Comment by moonmilker** [comment]
import base64
# Config

# API_INTERFACE = 'ehcomod'  # ehcomod <诞ݤ¹^̥±^̤¸^ԧ^Ԩ> # webapi
API_INTERFACE = 'webapi'  # ehcomod <诞ݤ¹^̥±^̤¸^ԧ^Ԩ> # webapi
UPDATE_TIME = 60


# Webapi token
USERNAME = 'bitcoinnoober'
PORT = 8388
try:
    TOKEN = base64.b64encode(
        bytes('{}+{}'.format(USERNAME, PORT), 'utf8')).decode()
except:
    TOKEN = base64.b64encode(
        bytes('{}+{}'.format(USERNAME, PORT))).decode()


WEBAPI_URL = 'http://1688ss.xyz/api'
NODE_ID = 1


# Mysql
MYSQL_CONFIG = 'configs/usermysql.json'

**Comment by moonmilker** [comment]
# 网站邀请界面提示语
INVITEINFO = '邀请码实时更新，如果用完了请关注公众号lalalal获取'

# 网站域名设置（请正确填写，不然订阅功能会失效：
HOST = 'http://1688ss.xyz'

# 管理员账号
USERNAME = 'bitcoinnoober'
# 管理员ss端口
PORT = 8388
# 管理员私有token，用于后端接口调用
TOKEN = base64.b64encode(
    bytes('{}+{}'.format(USERNAME, PORT), 'utf8')).decode()

**Comment by Ehco1996** [comment]
把你后端的 userapiconfig.py贴出来

**Comment by moonmilker** [comment]
要么是ID要么是node id就是2个数  都不行   前后端都放行了8388   网站是80端口
======================
import base64
# Config

# API_INTERFACE = 'ehcomod'  # ehcomod <诞ݤ¹^̥±^̤¸^ԧ^Ԩ> # webapi
API_INTERFACE = 'webapi'  # ehcomod <诞ݤ¹^̥±^̤¸^ԧ^Ԩ> # webapi
UPDATE_TIME = 60


# Webapi token
USERNAME = 'bitcoinnoober'
PORT = 8388
try:
    TOKEN = base64.b64encode(
        bytes('{}+{}'.format(USERNAME, PORT), 'utf8')).decode()
except:
    TOKEN = base64.b64encode(
        bytes('{}+{}'.format(USERNAME, PORT))).decode()


WEBAPI_URL = 'http://1688ss.xyz/api'
NODE_ID = 1


# Mysql
MYSQL_CONFIG = 'configs/usermysql.json'
# MUJSON API
MUAPI_CONFIG = 'usermuapi.json'
SERVER_PUB_ADDR = '127.0.0.1'  # mujson_mgr need this to generate ssr link

**Comment by Ehco1996** [comment]
node_id 设置成33

另外要确保 数据库里 有等级大于等于这个节点等级的用户

**Comment by moonmilker** [comment]
重新装一遍又遇到这个了 这次权限也是开了   密码是对的
运行python manage.py migrate出现这个错误  前几天更新好了   不知道怎么又这样了

Traceback (most recent call last):
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 236, in get_new_connection
    return Database.connect(**conn_params)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/MySQLdb/__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: NO)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/base.py", line 332, in execute
    self.check()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 57, in _run_checks
    issues = run_checks(tags=[Tags.database])
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/checks/database.py", line 10, in check_database_backends
    issues.extend(conn.validation.check(**kwargs))
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/mysql/validation.py", line 9, in check
    issues.extend(self._check_sql_mode(**kwargs))
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/mysql/validation.py", line 13, in _check_sql_mode
    with self.connection.cursor() as cursor:
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
    self.ensure_connection()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 236, in get_new_connection
    return Database.connect(**conn_params)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/MySQLdb/__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: NO)")
