### ISSUE TITLE
有两个问题想请教一下

### ISSUE THREAD

**Issue by Neveark** [Ehco1996/django-sspanel#119]
第一个问题是，在面板上添加了节点后，再进入查看节点(/sspanel/nodeinfo/)的页面，会提示Server Error (500)，删除全部节点就能显示页面，不知该如何解决，uwsgi提示:
[pid: 20357|app: 0|req: 84/110] *.*.*.* () {42 vars in 937 bytes} [Sun May 13 18:29:12 2018] GET /sspanel/backend/node/edit/1/ => generated 25750 bytes in 66 msecs (HTTP/1.1 200) 6 headers in 407 bytes (1 switches on core 1)

第二个问题是在配置节点，运行服务(python server.py)的时候会提示

2018-05-13 10:48:34 ERROR    db_transfer.py:293 Traceback (most recent call last):
  File "/root/shadowsocksr/transfer/db_transfer.py", line 275, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocksr/transfer/db_transfer.py", line 466, in pull_db_all_user
    db=self.cfg["db"], charset='utf8')
  File "/root/shadowsocksr/cymysql/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/root/shadowsocksr/cymysql/connections.py", line 245, in __init__
    self._connect()
  File "/root/shadowsocksr/cymysql/connections.py", line 413, in _connect
    self._request_authentication()
  File "/root/shadowsocksr/cymysql/connections.py", line 497, in _request_authentication
    auth_packet = self.read_packet()
  File "/root/shadowsocksr/cymysql/connections.py", line 418, in read_packet
    return MysqlPacket(self)
  File "/root/shadowsocksr/cymysql/packet.py", line 65, in __init__
    raise_mysql_exception(self.__data)
  File "/root/shadowsocksr/cymysql/err.py", line 149, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/root/shadowsocksr/cymysql/err.py", line 144, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
InternalError: (1043, u'Bad handshake')

也不知道怎么解决，已经配置好外部网络连接MySQL了
求大佬解答

**Comment by Ehco1996** [comment]
第一个大概是是数据库出错了，你进后台把所有节点删掉，重新加载就没问题了

第二个就是网络问题，要么是防火墙 要么是端口没开
