### ISSUE TITLE
修改密码发送邮件504

### ISSUE THREAD

**Issue by qiqizjl** [Ehco1996/django-sspanel#19]
用的是腾讯企业邮箱海外的
```
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# 我使用163邮箱作为smtp服务器
EMAIL_USE_TLS = True
EMAIL_HOST = 'hwsmtp.exmail.qq.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = '****'
EMAIL_HOST_PASSWORD = '****'
DEFAULT_FROM_EMAIL = '***'
```
也部署在海外服务器。 但是在找回密码的时候发送邮件就504了，而且之后访问也一直是504 需要重启panel才能恢复，请问下这个是什么问题？ 是无法连接SMTP么

**Comment by Ehco1996** [comment]
应该是vps连接不上smtp服务器
程序后台就会一直尝试重新发送
导致报错

**Comment by qiqizjl** [comment]
但是我尝试更换了阿里和腾讯的 都不行 海外的机器

**Comment by qiqizjl** [comment]
能否限制下重试的次数呢 不然以为就崩了。。

**Comment by Ehco1996** [comment]
@qiqizjl 
可以直接在vps服务器上查看下是否是smtp端口没开
如果开了还是发不出邮件的话
在simple_settings_product.py 里把debug模式打开
把log贴上来看看

下个版本会加上smtp服务的开关

**Comment by qiqizjl** [comment]
目前安全组都开放了 iptables关闭了 我打下log看下

**Comment by qiqizjl** [comment]
打开了Log uwsgi并没有输出额外的日志 也没有请求的log logs目录下也没多余的文件生成

**Comment by Ehco1996** [comment]
debug界面出来了么？
还是说你发送邮件的时候，网页会一直菊花，最后nginx 500报错？
可以看一下这里 ：[如何debug](https://github.com/Ehco1996/django-sspanel/wiki/%E5%A6%82%E4%BD%95%E6%AD%A3%E7%A1%AE%E7%9A%84debug)

**Comment by qiqizjl** [comment]
无限加载 然后504

**Comment by Ehco1996** [comment]
那一般就是服务商没开端口
可以用脚本测试一下发送smtp邮件
比如这样的

```python
#! /usr/bin/env python
#coding=utf-8

from email.mime.text import MIMEText
from email.header import Header
from smtplib import SMTP_SSL


#qq邮箱smtp服务器
host_server = 'smtp.qq.com'
#sender_qq为发件人的qq号码
sender_qq = '7697****@qq.com'
#pwd为qq邮箱的授权码
pwd = '****kenbb***' ## xh**********bdc
#发件人的邮箱
sender_qq_mail = '7697****@qq.com'
#收件人邮箱
receiver = 'yiibai.com@gmail.com'

#邮件的正文内容
mail_content = '你好，这是使用python登录qq邮箱发邮件的测试'
#邮件标题
mail_title = 'Maxsu的邮件'

#ssl登录
smtp = SMTP_SSL(host_server)
#set_debuglevel()是用来调试的。参数值为1表示开启调试模式，参数值为0关闭调试模式
smtp.set_debuglevel(1)
smtp.ehlo(host_server)
smtp.login(sender_qq, pwd)

msg = MIMEText(mail_content, "plain", 'utf-8')
msg["Subject"] = Header(mail_title, 'utf-8')
msg["From"] = sender_qq_mail
msg["To"] = receiver
smtp.sendmail(sender_qq_mail, receiver, msg.as_string())
smtp.quit()
```

**Comment by qiqizjl** [comment]
```
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    smtp = SMTP_SSL(host_server)
  File "/usr/local/lib/python3.6/smtplib.py", line 1029, in __init__
    source_address)
  File "/usr/local/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.6/smtplib.py", line 335, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.6/smtplib.py", line 1035, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
```
阿里云限制了？

**Comment by Ehco1996** [comment]
工单大法好

**Comment by qiqizjl** [comment]
@Ehco1996  我尝试在本机执行 也同样出错 难道是不支持ssl的smtp？

**Comment by qiqizjl** [comment]
```

Request Method: | POST
-- | --
http://proxy.mibbs.vip/password_reset/
1.11.4
TimeoutError
[Errno 110] Connection timed out
/usr/local/lib/python3.6/socket.py in create_connection, line 713
/usr/local/bin/uwsgi
3.6.1
['.',  '',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/site-packages']
星期一, 23 十月 2017 15:09:57 +0800


```
在服务器上能执行成功了 但是web却出错了

**Comment by qiqizjl** [comment]
根据django给出的smtp参数调整 已成功。。
将
```
EMAIL_USE_TLS = True
```
改成
```
#EMAIL_USE_TLS = True
EMAIL_USE_SSL = True
```
就好了 初步怀疑 QQ企业用的是ssl而不是tls

**Comment by qiqizjl** [comment]
看了下163和其他家 都是支持了SSL而不是TLS 要不把demo里的配置下改下？  不然TLS和SSL容易搞混。。

**Comment by Ehco1996** [comment]
好的，我会在下个版本加上
