### ISSUE TITLE
数据库分离时配置被覆盖

### ISSUE THREAD

**Issue by Isaccliberty** [Ehco1996/django-sspanel#194]
一台服务器A负责前段面板的运行，服务器B负责数据库
报错信息如下

 ` 
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django_prometheus/apps.py", line 24, in ready
    ExportMigrations()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django_prometheus/migrations.py", line 46, in ExportMigrations
    executor = MigrationExecutor(connections[alias])
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
    if self.has_table():
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 44, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
    self.ensure_connection()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django_prometheus/db/common.py", line 41, in get_new_connection
    *args, **kwargs)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/MySQLdb/connections.py", line 208, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2006, "Access denied for user 'panel'@'149.129.x.x' (using password: YES)") 
`

这个149的IP是A的，但是我配置文件里都是填写的B服务器的地址，这是不是配置被覆盖成了localhost

**Comment by Ehco1996** [comment]
数据库配置要卸载production.py里

**Comment by Isaccliberty** [comment]
> 数据库配置要写在production.py里

Worked！谢谢！
