### ISSUE TITLE
python manage.py migrate出错

### ISSUE THREAD

**Issue by zylok520** [Ehco1996/django-sspanel#203]
`(venv-sspanel) [root@host django-sspanel]# python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, jet, sessions, sspanel, ssserver
Running migrations:
Traceback (most recent call last):
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django_prometheus/db/common.py", line 63, in execute
    return super(CursorWrapper, self).execute(*args, **kwargs)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) NOT NULL)' at line 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 55, in ensure_schema
    editor.create_model(self.Migration)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 312, in create_model
    self.execute(sql, params or None)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 133, in execute
    cursor.execute(sql, params)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/raven/contrib/django/client.py", line 127, in execute
    return real_execute(self, sql, params)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/utils.py", line 83, in _execute
    return self.cursor.execute(sql)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django_prometheus/db/common.py", line 63, in execute
    return super(CursorWrapper, self).execute(*args, **kwargs)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) NOT NULL)' at line 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/migrations/executor.py", line 91, in migrate
    self.recorder.ensure_schema()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 57, in ensure_schema
    raise MigrationSchemaMissing("Unable to create the django_migrations table (%s)" % exc)
django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table ((1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) NOT NULL)' at line 1"))
(venv-sspanel) [root@host django-sspanel]# `

**Comment by zylok520** [comment]
CENTOS 7 64
mysql 5.5

**Comment by zyf19961209** [comment]
我也是遇到这个问题，数据库语法不对，不知道怎么解决

**Comment by zyf19961209** [comment]
我已经解决了，你查一下自己Django的版本是多少，然后安装对应版本的数据库

**Comment by zyf19961209** [comment]
Django  2.0就可以

**Comment by zylok520** [comment]
我的主机是512M内存，安装不了5.6.    我查了是SQL版本问题   ， 所以来在问问有什么好办法

**Comment by zylok520** [comment]
pip install django==2  用这个解决

**Comment by zylok520** [comment]
Installing collected packages: django
  Found existing installation: Django 2.1.5
    Uninstalling Django-2.1.5:
      Successfully uninstalled Django-2.1.5
Successfully installed django-2.0
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(venv-sspanel) [root@host django-sspanel]# python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, jet, sessions, sspanel, ssserver
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying sspanel.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying jet.0001_initial... OK
  Applying jet.0002_delete_userdashboardmodule... OK
  Applying sessions.0001_initial... OK
  Applying sspanel.0002_payrequest_qrcode_url... OK
  Applying sspanel.0003_auto_20181009_0909... OK
  Applying ssserver.0001_initial... OK
  Applying ssserver.0002_auto_20180707_2200... OK
  Applying ssserver.0003_auto_20180730_0916... OK
  Applying ssserver.0004_auto_20180930_1537... OK
/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField Suser.last_check_in_time received a naive datetime (1970-01-01 08:00:00) while time zone support is active.
  RuntimeWarning)
  Applying ssserver.0005_auto_20181003_1549... OK
  Applying ssserver.0006_auto_20181003_1759... OK
  Applying ssserver.0007_auto_20181004_1032... OK
  Applying ssserver.0008_auto_20181009_0909... OK
  Applying ssserver.0009_auto_20181122_0930... OK
(venv-sspanel) [root@host django-sspanel]#
