### ISSUE TITLE
执行docker-compose up后无法启动

### ISSUE THREAD

**Issue by HelloGit100** [Ehco1996/django-sspanel#218]
内容如下：
```
[root@centos django-sspanel]# docker-compose up
Creating network "django-sspanel_sspanel_network" with the default driver
Creating sspanel-db ... done
Creating sspanel-web ... done
Creating sspanel-nginx ... done
Attaching to sspanel-db, sspanel-web, sspanel-nginx
sspanel-db | 2019-03-03 02:42:54 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
sspanel-web | [uWSGI] getting INI configuration from uwsgi.ini
sspanel-db | 2019-03-03 02:42:54 0 [Note] mysqld (mysqld 5.6.43) starting as process 1 ...
sspanel-web | *** Starting uWSGI 2.0.18 (64bit) on [Sun Mar  3 02:42:54 2019] ***
sspanel-web | compiled with version: 8.2.0 on 03 March 2019 02:29:52
sspanel-web | os: Linux-4.20.2-1.el7.elrepo.x86_64 #1 SMP Sun Jan 13 09:57:55 EST 2019
sspanel-web | nodename: 8cff5e3693d7
sspanel-web | machine: x86_64
sspanel-web | clock source: unix
sspanel-web | detected number of CPU cores: 4
sspanel-web | current working directory: /src/django-sspanel
sspanel-web | writing pidfile to /tmp/django-sspanel.pid
sspanel-web | detected binary path: /usr/local/bin/uwsgi
sspanel-web | !!! no internal routing support, rebuild with pcre support !!!
sspanel-web | uWSGI running as root, you can use --uid/--gid/--chroot options
sspanel-web | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
sspanel-web | your memory page size is 4096 bytes
sspanel-web | detected max file descriptor number: 1048576
sspanel-web | - async cores set to 10 - fd table size: 1048576
sspanel-web | lock engine: pthread robust mutexes
sspanel-web | thunder lock: disabled (you can enable it with --thunder-lock)
sspanel-web | uwsgi socket 0 bound to TCP address web:8080 fd 3
sspanel-web | uWSGI running as root, you can use --uid/--gid/--chroot options
sspanel-web | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
sspanel-web | Python version: 3.6.8 (default, Feb  6 2019, 01:56:13)  [GCC 8.2.0]
sspanel-db | 2019-03-03 02:42:54 1 [Note] Plugin 'FEDERATED' is disabled.
sspanel-db | 2019-03-03 02:42:54 1 [Note] InnoDB: Using atomics to ref count buffer pool pages
sspanel-db | 2019-03-03 02:42:54 1 [Note] InnoDB: The InnoDB memory heap is disabled
sspanel-db | 2019-03-03 02:42:54 1 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
sspanel-db | 2019-03-03 02:42:54 1 [Note] InnoDB: Memory barrier is not used
sspanel-db | 2019-03-03 02:42:54 1 [Note] InnoDB: Compressed tables use zlib 1.2.11
sspanel-db | 2019-03-03 02:42:54 1 [Note] InnoDB: Using Linux native AIO
sspanel-db | 2019-03-03 02:42:54 1 [Note] InnoDB: Using CPU crc32 instructions
sspanel-web | Python main interpreter initialized at 0x55c2ac6a84e0
sspanel-web | uWSGI running as root, you can use --uid/--gid/--chroot options
sspanel-web | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
sspanel-web | python threads support enabled
sspanel-web | your server socket listen backlog is limited to 100 connections
sspanel-web | your mercy for graceful operations on workers is 60 seconds
sspanel-web | mapped 334048 bytes (326 KB) for 10 cores
sspanel-db | 2019-03-03 02:42:54 1 [Note] InnoDB: Initializing buffer pool, size = 128.0M
sspanel-web | *** Operational MODE: async ***
sspanel-db | 2019-03-03 02:42:54 1 [Note] InnoDB: Completed initialization of buffer pool
sspanel-db | 2019-03-03 02:42:54 1 [Note] InnoDB: Highest supported file format is Barracuda.
sspanel-db | 2019-03-03 02:42:54 1 [Note] InnoDB: 128 rollback segment(s) are active.
sspanel-db | 2019-03-03 02:42:54 1 [Note] InnoDB: Waiting for purge to start
sspanel-db | 2019-03-03 02:42:54 1 [Note] InnoDB: 5.6.43 started; log sequence number 1626057
sspanel-db | 2019-03-03 02:42:54 1 [Note] Server hostname (bind-address): '*'; port: 3306
sspanel-db | 2019-03-03 02:42:54 1 [Note] IPv6 is available.
sspanel-db | 2019-03-03 02:42:54 1 [Note]   - '::' resolves to '::';
sspanel-db | 2019-03-03 02:42:54 1 [Note] Server socket created on IP: '::'.
sspanel-db | 2019-03-03 02:42:54 1 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
sspanel-db | 2019-03-03 02:42:54 1 [Warning] 'proxies_priv' entry '@ root@e797827948bc' ignored in --skip-name-resolve mode.
sspanel-db | 2019-03-03 02:42:54 1 [Note] Event Scheduler: Loaded 0 events
sspanel-db | 2019-03-03 02:42:54 1 [Note] mysqld: ready for connections.
sspanel-db | Version: '5.6.43'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
sspanel-web | Traceback (most recent call last):
sspanel-web |   File "./apps/wsgi.py", line 17, in <module>
sspanel-web |     application = get_wsgi_application()
sspanel-web |   File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
sspanel-web |     django.setup(set_prefix=False)
sspanel-web |   File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
sspanel-web |     apps.populate(settings.INSTALLED_APPS)
sspanel-web |   File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
sspanel-web |     app_config.import_models()
sspanel-web |   File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
sspanel-web |     self.models_module = import_module(models_module_name)
sspanel-web |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
sspanel-web |     return _bootstrap._gcd_import(name[level:], package, level)
sspanel-web |   File "./apps/sspanel/models.py", line 16, in <module>
sspanel-web |     from apps.payments import pay
sspanel-web |   File "./apps/payments.py", line 38, in <module>
sspanel-web |     pay = Alipayments(APPID, PUBLIC_KEY_PATH, PRIVATE_KEY_PATH)
sspanel-web |   File "./apps/payments.py", line 24, in __init__
sspanel-web |     self.init_payment()
sspanel-web |   File "./apps/payments.py", line 34, in init_payment
sspanel-web |     debug=False,  # 默认False
sspanel-web |   File "/usr/local/lib/python3.6/site-packages/alipay/__init__.py", line 81, in __init__
sspanel-web |     self._load_key()
sspanel-web |   File "/usr/local/lib/python3.6/site-packages/alipay/__init__.py", line 87, in _load_key
sspanel-web |     with open(self._app_private_key_path) as fp:
sspanel-web | FileNotFoundError: [Errno 2] No such file or directory: '/src/django-sspanel/apps/App_pravite.pem'
sspanel-web | unable to load app 0 (mountpoint='') (callable not found or import error)
sspanel-web | *** no app loaded. going in full dynamic mode ***
sspanel-web | uWSGI running as root, you can use --uid/--gid/--chroot options
sspanel-web | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
sspanel-web | *** uWSGI is running in multiple interpreter mode ***
sspanel-web | spawned uWSGI master process (pid: 1)
sspanel-web | spawned uWSGI worker 1 (pid: 36, cores: 10)
sspanel-web | *** running gevent loop engine [addr:0x55c2abd20250] ***
```

谢谢

**Comment by Ehco1996** [comment]
需要在configs里吧 USE_ALIPAY 设置为False

**Comment by HelloGit100** [comment]
谢谢
