### ISSUE TITLE
App_pravite.pem这个文件怎么生成啊

### ISSUE THREAD

**Issue by jellywen2017** [Ehco1996/django-sspanel#219]
/src/django-sspanel # python3 manage.py createsuperuser
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/src/django-sspanel/apps/sspanel/models.py", line 16, in <module>
    from apps.payments import pay
  File "/src/django-sspanel/apps/payments.py", line 38, in <module>
    pay = Alipayments(APPID, PUBLIC_KEY_PATH, PRIVATE_KEY_PATH)
  File "/src/django-sspanel/apps/payments.py", line 24, in __init__
    self.init_payment()
  File "/src/django-sspanel/apps/payments.py", line 34, in init_payment
    debug=False,  # 默认False
  File "/usr/local/lib/python3.6/site-packages/alipay/__init__.py", line 81, in __init__
    self._load_key()
  File "/usr/local/lib/python3.6/site-packages/alipay/__init__.py", line 87, in _load_key
    with open(self._app_private_key_path) as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/src/django-sspanel/apps/App_pravite.pem'

**Comment by 1349422030** [comment]
请问你后来是怎么解决这个问题的？
