### ISSUE TITLE
运行python manage.py collectstatic后，后台admin的css样式表还是404报错

### ISSUE THREAD

**Issue by BlacK201** [Ehco1996/django-sspanel#231]
Found another file with the destination path 'admin/js/SelectFilter2.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/js/admin/RelatedObjectLookups.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/js/admin/DateTimeShortcuts.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/changelists.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/rtl.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/base.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/fonts.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/forms.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/widgets.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/dashboard.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/login.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.

394 static files copied to '/src/django-sspanel/static', 4 unmodified.

对应文件都是0B

[root@vultr /]# cd /root/django-sspanel/static/admin/css
[root@vultr css]# ll
total 40
-rw-r--r-- 1 root root  8440 May  5 16:17 autocomplete.css
-rw-r--r-- 1 root root     0 May  5 16:17 base.css
-rw-r--r-- 1 root root     0 May  5 16:17 changelists.css
-rw-r--r-- 1 root root     0 May  5 16:17 dashboard.css
-rw-r--r-- 1 root root     0 May  5 16:17 fonts.css
-rw-r--r-- 1 root root     0 May  5 16:17 forms.css
-rw-r--r-- 1 root root     0 May  5 16:17 login.css
-rw-r--r-- 1 root root 17944 May  5 16:17 responsive.css
-rw-r--r-- 1 root root  1921 May  5 16:17 responsive_rtl.css
-rw-r--r-- 1 root root     0 May  5 16:17 rtl.css
drwxr-xr-x 3 root root  4096 May  5 16:17 vendor
-rw-r--r-- 1 root root     0 May  5 16:17 widgets.css

**Comment by Ehco1996** [comment]
nginx的静态文件地址没写对


设置伪静态规则 将这一段复制填写进伪静态里

```
location /media  
    {        
        alias /home/www/django-sspanel/media;  # 媒体文件地址
    }    
location /static
    {    
        alias  /home/www/django-sspanel/static; #静态文件地址，js/css
        expires  12h;
    }    
location /
    {    
        include uwsgi_params;        
        uwsgi_pass 127.0.0.1:8080;
    }
```

**Comment by BlacK201** [comment]
我是使用docker来运行的，nginx.example.conf文件内容如下:
`	server {
        listen 2333;
        server_name _;
        root  /src/django-sspanel;
		if ($http_user_agent ~* "qihoobot|Baiduspider|Googlebot|Googlebot-Mobile|Googlebot-Image|Mediapartners-Google|Adsbot-Google|Feedfetcher-Google|Yahoo! Slurp|Yahoo! Slurp China|YoudaoBot|Sosospider|Sogou spider|Sogou web spider|MSNBot|ia_archiver|Tomato Bot") 
        {
        return 403;
        }
		location /media {
        alias /src/django-sspanel/media;  # your Django project's media files - amend as required
        }
		location /static {
		alias  /src/django-sspanel/static;
        expires  12h;
        }
        location / {
		include uwsgi_params;
        uwsgi_pass web:8080;
        }
    }`
里面应该是有对应的伪静态规则了啊...

**Comment by BlacK201** [comment]
我是使用docker来运行的，nginx.example.conf文件内容如下:
```
	server {
        listen 2333;
        server_name _;
        root  /src/django-sspanel;
		if ($http_user_agent ~* "qihoobot|Baiduspider|Googlebot|Googlebot-Mobile|Googlebot-Image|Mediapartners-Google|Adsbot-Google|Feedfetcher-Google|Yahoo! Slurp|Yahoo! Slurp China|YoudaoBot|Sosospider|Sogou spider|Sogou web spider|MSNBot|ia_archiver|Tomato Bot") 
        {
        return 403;
        }
		location /media {
        alias /src/django-sspanel/media;  # your Django project's media files - amend as required
        }
		location /static {
		alias  /src/django-sspanel/static;
        expires  12h;
        }
        location / {
		include uwsgi_params;
        uwsgi_pass web:8080;
        }
    }
```
里面应该是有对应的伪静态规则了啊...

**Comment by Ehco1996** [comment]
贴一下docker  niginx的日志上来看看

**Comment by BlacK201** [comment]
刚刚尝试了重新安装所以时间有点久，抱歉
```
root@76061a16031f:/var/log/nginx# cat host.access.log
116.136.20.163 - - [06/May/2019:04:31:56 +0000] "GET / HTTP/1.1" 200 6965 "http://myhost:2333/sspanel/sshelp/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3724.8 Safari/537.36" "-"
116.136.20.163 - - [06/May/2019:04:31:56 +0000] "GET /static/sspanel/css/ehco.css HTTP/1.1" 404 556 "http://myhost:2333/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3724.8 Safari/537.36" "-"
116.136.20.163 - - [06/May/2019:04:31:56 +0000] "GET /static/img/logo/logo.png HTTP/1.1" 404 556 "http://myhost:2333/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3724.8 Safari/537.36" "-"
116.136.20.163 - - [06/May/2019:04:31:56 +0000] "GET /static/sspanel/js/ehcov1.js HTTP/1.1" 404 556 "http://myhost:2333/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3724.8 Safari/537.36" "-"
116.136.20.163 - - [06/May/2019:04:32:00 +0000] "GET /admin/ HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3724.8 Safari/537.36" "-"
116.136.20.163 - - [06/May/2019:04:32:01 +0000] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 8449 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3724.8 Safari/537.36" "-"
116.136.20.163 - - [06/May/2019:04:32:01 +0000] "GET /admin/ HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3724.8 Safari/537.36" "-"
116.136.20.163 - - [06/May/2019:04:32:01 +0000] "GET /static/admin/css/base.css HTTP/1.1" 404 556 "http://myhost:2333/admin/login/?next=/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3724.8 Safari/537.36" "-"
116.136.20.163 - - [06/May/2019:04:32:01 +0000] "GET /static/jet/css/vendor.css?v=1.0.8 HTTP/1.1" 404 556 "http://myhost:2333/admin/login/?next=/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3724.8 Safari/537.36" "-"
116.136.20.163 - - [06/May/2019:04:32:01 +0000] "GET /static/jet/css/icons/style.css?v=1.0.8 HTTP/1.1" 404 556 "http://myhost:2333/admin/login/?next=/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3724.8 Safari/537.36" "-"
116.136.20.163 - - [06/May/2019:04:32:01 +0000] "GET /static/jet/css/themes/default/base.css?v=1.0.8 HTTP/1.1" 404 556 "http://myhost:2333/admin/login/?next=/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3724.8 Safari/537.36" "-"
116.136.20.163 - - [06/May/2019:04:32:01 +0000] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 8449 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3724.8 Safari/537.36" "-"
116.136.20.163 - - [06/May/2019:04:32:01 +0000] "GET /static/jet/css/themes/default/select2.theme.css?v=1.0.8 HTTP/1.1" 404 556 "http://myhost:2333/admin/login/?next=/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3724.8 Safari/537.36" "-"
116.136.20.163 - - [06/May/2019:04:32:01 +0000] "GET /static/jet/css/themes/default/jquery-ui.theme.css?v=1.0.8 HTTP/1.1" 404 556 "http://myhost:2333/admin/login/?next=/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3724.8 Safari/537.36" "-"
116.136.20.163 - - [06/May/2019:04:32:01 +0000] "GET /static/admin/css/login.css HTTP/1.1" 404 556 "http://myhost:2333/admin/login/?next=/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3724.8 Safari/537.36" "-"
116.136.20.163 - - [06/May/2019:04:32:01 +0000] "GET /jet/jsi18n/ HTTP/1.1" 200 7722 "http://myhost:2333/admin/login/?next=/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3724.8 Safari/537.36" "-"
116.136.20.163 - - [06/May/2019:04:32:01 +0000] "GET /static/jet/js/build/bundle.min.js?v=1.0.8 HTTP/1.1" 404 556 "http://myhost:2333/admin/login/?next=/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3724.8 Safari/537.36" "-"
116.136.20.163 - - [06/May/2019:04:32:01 +0000] "GET /favicon.ico HTTP/1.1" 200 43 "http://myhost:2333/admin/login/?next=/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3724.8 Safari/537.36" "-"
```

**Comment by Ehco1996** [comment]
@BlacK201 

我发现是我statistics的目录挂载的不对，拉一下dev分支就能用了

**Comment by BlacK201** [comment]
从头开始以后又遇到了这个问题...
是我配置文件有哪个写错了吗
```
[root@vultr django-sspanel]# docker-compose run web python manage.py migrate
Starting mysql ... done
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/src/app/apps/ssserver/models.py", line 22, in <module>
    from apps.encoder import encoder
  File "/usr/src/app/apps/encoder.py", line 16, in <module>
    encoder = Encoder(alphabet=settings.DEFAULT_ALPHABET)
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 80, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'DEFAULT_ALPHABET'
```

**Comment by Ehco1996** [comment]
看下 configs/default/sites.py
里是不是没有 `DEFAULT_ALPHABET` 这个配置项

**Comment by BlacK201** [comment]
是的。。

**Comment by Ehco1996** [comment]
拉一下最新的dev分支就行了，应该是你处理冲突的时候覆盖掉了

**Comment by BlacK201** [comment]
migrate过了以后，collectstatic还是有这一堆。。
而且运行到这里以后，一直是等待输入的状态没有跳回bash
```
[root@vultr django-sspanel]# docker-compose run web python manage.py collectstatic
Starting mysql ... done

You have requested to collect static files at the destination
location as specified in your settings:

    /usr/src/app/static

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Found another file with the destination path 'admin/js/SelectFilter2.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/js/admin/RelatedObjectLookups.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/js/admin/DateTimeShortcuts.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/changelists.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/rtl.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/base.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/fonts.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/forms.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/widgets.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/dashboard.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'admin/css/login.css'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.

394 static files copied to '/usr/src/app/static', 4 unmodified.
```

**Comment by BlacK201** [comment]
尝试Ctrl+C退出以后，创建超级用户完成也是一样的状况，一直等待输入。
进后台还是没css，查看css文件还是0B...

**Comment by Ehco1996** [comment]
1 docker-compose up -d
2 docker-compose exec web sh  
3 python manage.py collectstatic

**Comment by BlacK201** [comment]
emm我照做了还是没有。。

**Comment by Ehco1996** [comment]
加我tg https://t.me/ehco1996
