### ISSUE TITLE
感觉是mysql的版本问题，提交一个bug，生成数据库的时候发生的。

### ISSUE THREAD

**Issue by l764191074** [Ehco1996/django-sspanel#25]
Applying shadowsocks.0002_node_show...Traceback (most recent call last):
  File "/home/usr/python36/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/usr/python36/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/home/usr/python36/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/usr/python36/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/home/usr/python36/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/home/usr/python36/lib/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/home/usr/python36/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/home/usr/python36/lib/python3.6/site-packages/MySQLdb/connections.py", line 292, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1067, "Invalid default value for 'show'")

**Comment by Ehco1996** [comment]
是因为增量更新是migrations文件有冲突
刚更新的版本已经修复了
