### ISSUE TITLE
关于用面板部署的时候启动的问题

### ISSUE THREAD

**Issue by JummyWu** [Ehco1996/django-sspanel#255]
```
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/root/.pyenv/versions/3.6.3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/jet/models.py", line 3, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible'
```
按照着上面的教程，走到启动时候报错的

**Comment by Ehco1996** [comment]
代码没有升级到最新

最新版本的代码已经移除了django-jet这个依赖

**Comment by JummyWu** [comment]
> 代码没有升级到最新
> 
> 最新版本的代码已经可移除了django-jet这个依赖

请问是需要用那个分支呢？
