### ISSUE TITLE
节点安装时地址被占用

### ISSUE THREAD

**Issue by SmallDS** [Ehco1996/django-sspanel#266]
] protocol [origin] method [aes-128-cfb] obfs [plain]
2020-02-04 12:32:19 INFO     server_pool.py:146 starting server at [::]:22286
2020-02-04 12:32:19 WARNING  server_pool.py:161 IPV6 [Errno 98] Address already in use 
2020-02-04 12:32:19 INFO     server_pool.py:176 starting server at 0.0.0.0:22286
2020-02-04 12:32:19 WARNING  server_pool.py:190 IPV4 [Errno 98] Address already in use 
2020-02-04 12:32:19 INFO     web_transfer.py:615 db start server at port [14221] pass [xxiMsr] protocol [origin] method [aes-128-cfb] obfs [plain]
2020-02-04 12:32:19 INFO     server_pool.py:146 starting server at [::]:14221
2020-02-04 12:32:19 WARNING  server_pool.py:161 IPV6 [Errno 98] Address already in use 
2020-02-04 12:32:19 INFO     server_pool.py:176 starting server at 0.0.0.0:14221
2020-02-04 12:32:19 WARNING  server_pool.py:190 IPV4 [Errno 98] Address already in use 
2020-02-04 12:33:15 ERROR    webapi_utils.py:38 Traceback (most recent call last):
  File "/root/shadowsocks/webapi_utils.py", line 23, in getApi
    timeout=10)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 498, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 486, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 598, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine("''",))

2020-02-04 12:33:15 ERROR    auto_block.py:293 Traceback (most recent call last):
  File "/root/shadowsocks/auto_block.py", line 289, in thread_db
    db_instance.auto_block_thread()
  File "/root/shadowsocks/auto_block.py", line 45, in auto_block_thread
    data = webapi.getApi('nodes')
  File "/root/shadowsocks/webapi_utils.py", line 39, in getApi
    raise Exception('network issue or server error!')
Exception: network issue or server error!

已经关闭了防火墙了

**Comment by Ehco1996** [comment]
这个面板不支持ssr，只和我开发的ss兼容 https://github.com/Ehco1996/aioshadowsocks
