### ISSUE TITLE
小白求教。

### ISSUE THREAD

**Issue by eric21** [Ehco1996/django-sspanel#3]
# pyenv virtualenv 3.6.1 venv-sspanel
pyenv: no such command `virtualenv'
到这句就不对了。我手动安装了virtualenv，还是不行，是不是哪里需要设置virtualenv的安装路径？

**Comment by Ehco1996** [comment]
@eric21 
如果你按照pyenv的正确安装步骤，应该不会有问题，
如果显示没有该命令 尝试重启一下 bash

还有问题可以看这个 issues： https://github.com/pyenv/pyenv-virtualenv/issues/25

**Comment by eric21** [comment]
git clone https://github.com/yyuu/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv

亲测这句有效。我继续下面的步骤

**Comment by eric21** [comment]
# pip install -r /home/www/django-sspanel/requirements.txt
Collecting cycler==0.10.0 (from -r /home/www/django-sspanel/requirements.txt (line 1))
  Using cached cycler-0.10.0-py2.py3-none-any.whl
Collecting Django==1.11.3 (from -r /home/www/django-sspanel/requirements.txt (line 2))
  Using cached Django-1.11.3-py2.py3-none-any.whl
Collecting image==1.5.11 (from -r /home/www/django-sspanel/requirements.txt (line 3))
  Using cached image-1.5.11-py2.py3-none-any.whl
Collecting mysqlclient==1.3.10 (from -r /home/www/django-sspanel/requirements.txt (line 4))
  Using cached mysqlclient-1.3.10.tar.gz
    Complete output from command python setup.py egg_info:
    sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-e4bGwC/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-e4bGwC/mysqlclient/

到这里又报错了。
尝试
pip install --upgrade setuptools
pip install ez_setup
pip install unroll
这3个命令后问题依旧。
是不是因为lnmp里面的mysql安装目录不对？

**Comment by Ehco1996** [comment]
@eric21 

是 mysql client 包出了问题，
安装这个包之前需要安装 Python dev

具体看这里 https://github.com/PyMySQL/mysqlclient-python

**Comment by eric21** [comment]
成功安装mysql client,继续下一步

**Comment by eric21** [comment]
\# python ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/www/django-sspanel/django_sspanel/settings.py", line 14
SyntaxError: Non-ASCII character '\xe5' in file /home/www/django-sspanel/django_sspanel/settings.py on line 14, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

---------------------------
# python ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/usr/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/www/django-sspanel/shadowsocks/models.py", line 5
SyntaxError: Non-ASCII character '\xe8' in file /home/www/django-sspanel/shadowsocks/models.py on line 5, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
-----------------------------------------
# python ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/usr/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/www/django-sspanel/shadowsocks/models.py", line 5, in <module>
    from .tools import get_long_random_string, get_short_random_string
  File "/home/www/django-sspanel/shadowsocks/tools.py", line 10
SyntaxError: Non-ASCII character '\xe5' in file /home/www/django-sspanel/shadowsocks/tools.py on line 11, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
------------------------------
# python ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/usr/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/www/django-sspanel/ssserver/models.py", line 1
SyntaxError: Non-ASCII character '\xe8' in file /home/www/django-sspanel/ssserver/models.py on line 1, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
------------------------------
# python ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/usr/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python2.7/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/usr/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/usr/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/www/django-sspanel/ssserver/admin.py", line 10
SyntaxError: Non-ASCII character '\xe6' in file /home/www/django-sspanel/ssserver/admin.py on line 10, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
-----------------------------
提示了几个注解符号错误,这都不要紧..

# python ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 61, in _run_checks
    issues = run_checks(tags=[Tags.database])
  File "/usr/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/lib/python2.7/site-packages/django/core/checks/database.py", line 10, in check_database_backends
    issues.extend(conn.validation.check(**kwargs))
  File "/usr/lib/python2.7/site-packages/django/db/backends/mysql/validation.py", line 9, in check
    issues.extend(self._check_sql_mode(**kwargs))
  File "/usr/lib/python2.7/site-packages/django/db/backends/mysql/validation.py", line 13, in _check_sql_mode
    with self.connection.cursor() as cursor:
  File "/usr/lib/python2.7/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/usr/lib/python2.7/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/usr/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/lib/python2.7/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 274, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
但是最后,貌似是哪个文件没有设置mysql密码?

**Comment by eric21** [comment]
感谢巨巨的耐心解答
