### ISSUE TITLE
docker 安装 docker-compose up -d 启动后 日志显示连接MySQL失败

### ISSUE THREAD

**Issue by t822876884** [Ehco1996/django-sspanel#326]
Attaching to web
web      | [uWSGI] getting INI configuration from uwsgi.ini
web      | Sun May 17 04:32:21 2020 - *** Starting uWSGI 2.0.18 (64bit) on [Sun May 17 04:32:21 2020] ***
web      | Sun May 17 04:32:21 2020 - compiled with version: 9.2.0 on 22 March 2020 01:51:33
web      | Sun May 17 04:32:21 2020 - os: Linux-3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020
web      | Sun May 17 04:32:21 2020 - nodename: b33586b64be1
web      | Sun May 17 04:32:21 2020 - machine: x86_64
web      | Sun May 17 04:32:21 2020 - clock source: unix
web      | Sun May 17 04:32:21 2020 - detected number of CPU cores: 1
web      | Sun May 17 04:32:21 2020 - current working directory: /usr/src/app
web      | Sun May 17 04:32:21 2020 - writing pidfile to /tmp/django-sspanel.pid
web      | Sun May 17 04:32:21 2020 - detected binary path: /usr/local/bin/uwsgi
web      | Sun May 17 04:32:21 2020 - !!! no internal routing support, rebuild with pcre support !!!
web      | Sun May 17 04:32:21 2020 - uWSGI running as root, you can use --uid/--gid/--chroot options
web      | Sun May 17 04:32:21 2020 - *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
web      | Sun May 17 04:32:21 2020 - your memory page size is 4096 bytes
web      | Sun May 17 04:32:21 2020 - detected max file descriptor number: 1048576
web      | Sun May 17 04:32:21 2020 - - async cores set to 10 - fd table size: 1048576
web      | Sun May 17 04:32:21 2020 - lock engine: pthread robust mutexes
web      | Sun May 17 04:32:21 2020 - thunder lock: disabled (you can enable it with --thunder-lock)
web      | Sun May 17 04:32:21 2020 - uwsgi socket 0 bound to TCP address 0.0.0.0:8080 fd 3
web      | Sun May 17 04:32:21 2020 - uWSGI running as root, you can use --uid/--gid/--chroot options
web      | Sun May 17 04:32:21 2020 - *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
web      | Sun May 17 04:32:21 2020 - Python version: 3.7.7 (default, Mar 11 2020, 01:01:39)  [GCC 9.2.0]
web      | Sun May 17 04:32:21 2020 - Python main interpreter initialized at 0x55560a60e460
web      | Sun May 17 04:32:21 2020 - uWSGI running as root, you can use --uid/--gid/--chroot options
web      | Sun May 17 04:32:21 2020 - *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
web      | Sun May 17 04:32:21 2020 - python threads support enabled
web      | Sun May 17 04:32:21 2020 - your server socket listen backlog is limited to 100 connections
web      | Sun May 17 04:32:21 2020 - your mercy for graceful operations on workers is 60 seconds
web      | Sun May 17 04:32:21 2020 - mapped 334048 bytes (326 KB) for 10 cores
web      | Sun May 17 04:32:21 2020 - *** Operational MODE: async ***
web      | Traceback (most recent call last):
web      |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
web      |     self.connect()
web      |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
web      |     return func(*args, **kwargs)
web      |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 197, in connect
web      |     self.connection = self.get_new_connection(conn_params)
web      |   File "/usr/local/lib/python3.7/site-packages/django_prometheus/db/common.py", line 44, in get_new_connection
web      |     return super(DatabaseWrapperMixin, self).get_new_connection(*args, **kwargs)
web      |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
web      |     return func(*args, **kwargs)
web      |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 233, in get_new_connection
web      |     return Database.connect(**conn_params)
web      |   File "/usr/local/lib/python3.7/site-packages/MySQLdb/__init__.py", line 84, in Connect
web      |     return Connection(*args, **kwargs)
web      |   File "/usr/local/lib/python3.7/site-packages/MySQLdb/connections.py", line 179, in __init__
web      |     super(Connection, self).__init__(*args, **kwargs2)
web      | MySQLdb._exceptions.OperationalError: (2002, "Can't connect to MySQL server on 'mysql' (115)")
web      | 
web      | The above exception was the direct cause of the following exception:
web      | 
web      | Traceback (most recent call last):
web      |   File "./apps/wsgi.py", line 15, in <module>
web      |     application = get_wsgi_application()
web      |   File "/usr/local/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
web      |     django.setup(set_prefix=False)
web      |   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
web      |     apps.populate(settings.INSTALLED_APPS)
web      |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 122, in populate
web      |     app_config.ready()
web      |   File "/usr/local/lib/python3.7/site-packages/django_prometheus/apps.py", line 23, in ready
web      |     ExportMigrations()
web      |   File "/usr/local/lib/python3.7/site-packages/django_prometheus/migrations.py", line 49, in ExportMigrations
web      |     executor = MigrationExecutor(connections[alias])
web      |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
web      |     self.loader = MigrationLoader(self.connection)
web      |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
web      |     self.build_graph()
web      |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 212, in build_graph
web      |     self.applied_migrations = recorder.applied_migrations()
web      |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 76, in applied_migrations
web      |     if self.has_table():
web      |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 56, in has_table
web      |     return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
web      |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
web      |     return func(*args, **kwargs)
web      |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 260, in cursor
web      |     return self._cursor()
web      |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 236, in _cursor
web      |     self.ensure_connection()
web      |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
web      |     return func(*args, **kwargs)
web      |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
web      |     self.connect()
web      |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
web      |     raise dj_exc_value.with_traceback(traceback) from exc_value
web      |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
web      |     self.connect()
web      |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
web      |     return func(*args, **kwargs)
web      |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 197, in connect
web      |     self.connection = self.get_new_connection(conn_params)
web      |   File "/usr/local/lib/python3.7/site-packages/django_prometheus/db/common.py", line 44, in get_new_connection
web      |     return super(DatabaseWrapperMixin, self).get_new_connection(*args, **kwargs)
web      |   File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
web      |     return func(*args, **kwargs)
web      |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 233, in get_new_connection
web      |     return Database.connect(**conn_params)
web      |   File "/usr/local/lib/python3.7/site-packages/MySQLdb/__init__.py", line 84, in Connect
web      |     return Connection(*args, **kwargs)
web      |   File "/usr/local/lib/python3.7/site-packages/MySQLdb/connections.py", line 179, in __init__
web      |     super(Connection, self).__init__(*args, **kwargs2)
web      | django.db.utils.OperationalError: (2002, "Can't connect to MySQL server on 'mysql' (115)")
web      | Sun May 17 04:32:26 2020 - unable to load app 0 (mountpoint='') (callable not found or import error)
web      | Sun May 17 04:32:26 2020 - *** no app loaded. going in full dynamic mode ***
web      | Sun May 17 04:32:26 2020 - uWSGI running as root, you can use --uid/--gid/--chroot options
web      | Sun May 17 04:32:26 2020 - *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
web      | Sun May 17 04:32:26 2020 - *** uWSGI is running in multiple interpreter mode ***
web      | Sun May 17 04:32:26 2020 - spawned uWSGI master process (pid: 1)
web      | Sun May 17 04:32:26 2020 - spawned uWSGI worker 1 (pid: 9, cores: 10)
web      | Sun May 17 04:32:26 2020 - *** running gevent loop engine [addr:0x55560a196770] ***
web      | Sun May 17 05:11:25 2020 - invalid request block size: 21573 (max 4096)...skip

**Comment by t822876884** [comment]
执行命令的过程
--安装依赖
yum -y install nano git wget

--更新系统
yum -y update

--安装docker
curl -sSL https://get.docker.com/ |sh

sudo curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-Linux-x86_64" -o /usr/local/bin/docker-compose

sudo chmod +x /usr/local/bin/docker-compose

--自启动
systemctl enable docker

--启动docker
systemctl start docker

--下载源码
git clone https://github.com/Ehco1996/django-sspanel.git

cd django-sspanel/

-- 启动
docker-compose up -d

docker-compose ps

docker-compose logs -f web

**Comment by t822876884** [comment]
可能是没有权限，可以先启动mysql，放开权限，然后启动其他项目
-- 启动
docker-compose up -d mysql

-- 授权 MySQL start --
docker-compose exec mysql bash

mysql -u root -p

键入root密码

grant all privileges on *.* to root@"%" identified by "yourpass" with grant option;
--授权 MySQL end --

--启动其他项目
docker-compose up -d web nginx cron
