### ISSUE TITLE
开debug运行，程序直接报500错误

### ISSUE THREAD

**Issue by cheapssr** [Ehco1996/django-sspanel#35]
GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)

**Comment by cheapssr** [comment]
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "./django-sspanel/wsgi.py 

", line 16, in <module>
    application = get_wsgi_application()
  File "/root/.pyenv/versions/3.6.1/envs/venv-sspanel/lib/python3.6/site-packages/django/core/wsgi.py 

", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/root/.pyenv/versions/3.6.1/envs/venv-sspanel/lib/python3.6/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/root/.pyenv/versions/3.6.1/envs/venv-sspanel/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/root/.pyenv/versions/3.6.1/envs/venv-sspanel/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/root/.pyenv/versions/3.6.1/envs/venv-sspanel/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/root/.pyenv/versions/3.6.1/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "./django-sspanel/settings.py 

", line 19, in <module>
    from.simple_setting_product import *
  File "./django-sspanel/simple_setting_product.py 

", line 2, in <module>
    DEBUG = true
NameError: name 'true' is not defined

**Comment by cheapssr** [comment]
这是多个域名建站的

**Comment by Ehco1996** [comment]
是True 
不是true
