### ISSUE TITLE
执行docker-compose命令时报错 No module named 'debug_toolbar'

### ISSUE THREAD

**Issue by PengsongAndroid** [Ehco1996/django-sspanel#530]
celery-worker    |   File "/usr/src/app/apps/urls.py", line 14, in <module>
celery-worker    |     import debug_toolbar
celery-worker    | ModuleNotFoundError: No module named 'debug_toolbar'

**Comment by PengsongAndroid** [comment]
Creating mysql ... done
Creating redis ... done
Creating django-sspanel_web_run ... done
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'debug_toolbar'
ERROR: 1

**Comment by lynkco01** [comment]
遇到同样的报错问题
# docker-compose run --rm web python manage.py collectstatic --noinput
Creating django-sspanel_web_run ... done
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'debug_toolbar'
ERROR: 1

**Comment by Ehco1996** [comment]
@lynkco01 @PengsongAndroid 

应该是你们的 compose 的版本太低了，可以手动把`DJANGO_ENV`这个环境变量设置为 `production`

**Comment by lynkco01** [comment]
docker-compose 版本是：
docker-compose version 1.29.2, build 5becea4c
修改环境变量后貌似问题依然没有解决，报错信息还是一样的。

**Comment by Gkirito** [comment]
> @lynkco01 @PengsongAndroid
> 
> 应该是你们的 compose 的版本太低了，可以手动把`DJANGO_ENV`这个环境变量设置为 `production`

要不在dockerfile里设置好ENV吧，这样防止出问题

**Comment by PengsongAndroid** [comment]
同上docker-compose version 1.29.2, build 5becea4c，环境修改了还是会报错

**Comment by Ehco1996** [comment]
@PengsongAndroid  @lynkco01 

的确是代码有点问题， 已经修复了拉一下最新的代码就好

**Comment by lynkco01** [comment]
问题已解决，大佬辛苦了。

**Comment by PengsongAndroid** [comment]
> 问题已解决，大佬辛苦了。

老哥你这边没报错了吗 我执行`docker-compose run --rm web python manage.py migrate`会报错
`root@VerifiableBlind-VM:~/django-sspanel# docker-compose run --rm web python manage.py migrate
Creating django-sspanel_web_run ... done
SystemCheckError: System check identified some issues:

ERRORS:
proxy.UserTrafficLog: (fields.E180) MySQL does not support JSONFields.
`
