### ISSUE TITLE
(1045, "Access denied for user 'root'@'172.18.0.4' (using password: YES)")

### ISSUE THREAD

**Issue by taotecode** [Ehco1996/django-sspanel#603]
**问题的描述**
(1045, "Access denied for user 'root'@'172.18.0.4' (using password: YES)")
**项目的配置文件**
```
#--->服务端口 nginx
port=8080

#--->mysql
# mysql数据库设置 db.py
MYSQL_USER=root
MYSQL_PASSWORD=yourpass
# mysql服务设置
# mysql host默认请保持注释*
# MYSQL_HOS=mysql
# mysql服务密码设置
MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
#设置MYSQL_PASSWORD即可


#--->网站定制 sites.py
# 网站域名设置（请正确填写，不然订阅功能会失效：
HOST=http://127.0.0.1
# 网站密钥
SECRET_KEY=aasdasdas
# 是否开启注册
ALLOW_REGISTER=True
# 默认的theme
# 可选列表在 apps/constants.py 里的THEME_CHOICES里
DEFAULT_THEME=default
# 默认加密混淆协议
DEFAULT_METHOD=aes-256-cfb
# 签到流量设置
MIN_CHECKIN_TRAFFIC=10485760
# 10 * 1024 * 1024 (10MB)
MAX_CHECKIN_TRAFFIC=209715200
# 200 * 1024 * 1024 (200MB)
# 网站title
TITLE=谜之屋
SUBTITLE=秘密的小屋
# 用户邀请返利比例
INVITE_PERCENT=0.2
# 用户能生成的邀请码数量
INVITE_NUM=5
# 网站邀请页提示语
INVITEINFO=邀请码实时更新，如果用完了就没了
# 部分API接口TOKEN
TOKEN=youowntoken
# SHORT_URL_ALPHABET 请随机生成,且不要重复
DEFAULT_ALPHABET=qwertyuiopasdfghjklzxcvbnm
# FOR SIMPLE UI
SIMPLEUI_HOME_INFO=False
SIMPLEUI_DEFAULT_ICON=False
# 是否开启用户到期邮件通知
EXPIRE_EMAIL_NOTICE=False


#--->邮箱设置 email.py
# 是否开启邮件功能
USE_SMTP=True
EMAIL_USE_SSL=True
EMAIL_HOST=smtp.163.com
EMAIL_PORT=465
EMAIL_HOST_USER=user
EMAIL_HOST_PASSWORD=yourpass
DEFAULT_FROM_EMAIL=user      #可以与EMAIL_HOST_USER一致
# FOR mailgun*
# MAILGUN_API_KEY=key
# MAILGUN_SENDER_DOMAIN=domain


#--->支付宝对接 pay.py*
#USE_ALIPAY = False
#CHECK_PAY_REQ_IP_FROM_CN = False
#ALIPAY_APP_ID = XXXXXXXX
#ALIPAY_APP_PRIVATE_KEY_STRING = "-----BEGIN RSA PRIVATE KEY-----
#-----END RSA PRIVATE KEY-----"
#ALIPAY_PUBLIC_KEY_STRING="-----BEGIN PUBLIC KEY-----
#-----END PUBLIC KEY-----"
ALIPAY_TRADE_INFO="{}元充值码"

#--->其他*
# 时区
#TZ = Asia/Shanghai
# msyql host
#MYSQL_HOST = mysql
# redis host
#REDIS_HOST = redis
# production不开启debug，development开启debug
#DJANGO_ENV = production
```
**如何复现**
```
docker-compose run --rm web python manage.py collectstatic --noinput
```
**相关截图/log**
```
Pulling mysql (mysql:5.7)...
5.7: Pulling from library/mysql
ffbb094f4f9e: Pull complete
df186527fc46: Pull complete
fa362a6aa7bd: Pull complete
5af7cb1a200e: Pull complete
949da226cc6d: Pull complete
bce007079ee9: Pull complete
eab9f076e5a3: Pull complete
c7b24c3f27af: Pull complete
6fc26ff6705a: Pull complete
bec5cdb5e7f7: Pull complete
6c1cb25f7525: Pull complete
Digest: sha256:d1cc87a3bd5dc07defc837bc9084f748a130606ff41923f46dec1986e0dc828d
Status: Downloaded newer image for mysql:5.7
Starting redis ... done
Creating mysql ... done
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django_prometheus/db/common.py", line 45, in get_new_connection
    return super().get_new_connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'root'@'172.18.0.4' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/usr/local/lib/python3.8/site-packages/django_prometheus/apps.py", line 23, in ready
    ExportMigrations()
  File "/usr/local/lib/python3.8/site-packages/django_prometheus/migrations.py", line 52, in ExportMigrations
    executor = MigrationExecutor(connections[alias])
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 220, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 55, in has_table
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django_prometheus/db/common.py", line 45, in get_new_connection
    return super().get_new_connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 130, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1045, "Access denied for user 'root'@'172.18.0.4' (using password: YES)")
```
**其他信息**
Docker version 20.10.11, build dea9396
docker-compose version 1.24.1, build 4667896b

**Comment by taotecode** [comment]
.env.sample
里面也包含太多空格了

**Comment by Ehco1996** [comment]
> .env.sample 里面也包含太多空格了

可能就是空格太多导致密码没穿进去，你可以提个 pr 改一下么

**Comment by taotecode** [comment]
> > .env.sample 里面也包含了多重
> 
> 可能就是打包导致密码没穿进去，你可以提一个改一下么

这个是可以的，不过这个数据库连接没搞懂

**Comment by taotecode** [comment]
> > .env.sample 里面也包含太多空格了
> 
> 可能就是空格太多导致密码没穿进去，你可以提个 pr 改一下么

#604

**Comment by Ehco1996** [comment]
closed due to https://github.com/Ehco1996/django-sspanel/pull/604
