### ISSUE TITLE
docker-compose up 启动报错

### ISSUE THREAD

**Issue by Alioth1017** [Ehco1996/django-sspanel#618]
**问题的描述**
项目拉取最新镜像后启动报错

**项目的配置文件**
-

**如何复现**
本项目拉取代码后，初始化站点操作到最后一步 docker-compose up 
celery-beat、celery-worker 2个容器一直报错重启

**相关截图/log**
![1641924991(1)](https://user-images.githubusercontent.com/10696356/148998844-8d19fdee-11d5-4ab1-9171-f0031d156018.png)
![1641925003(1)](https://user-images.githubusercontent.com/10696356/148998855-fe1ed2ab-a84b-443d-8222-df61f3801e82.png)

**其他信息**

```bash
celery-beat    | Usage: celery [OPTIONS] COMMAND [ARGS]...

celery-beat    | 

celery-beat    | Error: Invalid value for '-A' / '--app': 

celery-beat    | Unable to load celery application.

celery-beat    | While trying to load the module apps the following error occurred:

celery-beat    | Traceback (most recent call last):

celery-beat    |   File "/usr/local/lib/python3.8/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name

celery-beat    |     module = imp(module_name, package=package, **kwargs)

celery-beat    |   File "/usr/local/lib/python3.8/site-packages/celery/utils/imports.py", line 100, in import_from_cwd

celery-beat    |     return imp(module, package=package)

celery-beat    |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module

celery-beat    |     return _bootstrap._gcd_import(name[level:], package, level)

celery-beat    |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

celery-beat    |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load

celery-beat    |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

celery-beat    |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

celery-beat    |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module

celery-beat    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

celery-beat    |   File "/usr/src/app/apps/__init__.py", line 1, in <module>

celery-beat    |     from apps.celery import app as celery_app

celery-beat    |   File "/usr/src/app/apps/celery.py", line 5, in <module>

celery-beat    |     from configs.default.cron import task_schedule

celery-beat    |   File "/usr/src/app/configs/__init__.py", line 3, in <module>

celery-beat    |     from configs.default import *  # noqa

celery-beat    |   File "/usr/src/app/configs/default/__init__.py", line 9, in <module>

celery-beat    |     from .sites import *  # noqa isort:skip

celery-beat    |   File "/usr/src/app/configs/default/sites.py", line 30, in <module>

celery-beat    |     MIN_CHECKIN_TRAFFIC = int(os.getenv("MIN_CHECKIN_TRAFFIC", 10 * MB))

celery-beat    | ValueError: invalid literal for int() with base 10: '10485760   # 10 * 1024 * 1024 (10MB)'

celery-beat    | 

celery-beat    | During handling of the above exception, another exception occurred:

celery-beat    | 

celery-beat    | Traceback (most recent call last):

celery-beat    |   File "/usr/local/lib/python3.8/site-packages/celery/bin/celery.py", line 53, in convert

celery-beat    |     return find_app(value)

celery-beat    |   File "/usr/local/lib/python3.8/site-packages/celery/app/utils.py", line 384, in find_app

celery-beat    |     sym = symbol_by_name(app, imp=imp)

celery-beat    |   File "/usr/local/lib/python3.8/site-packages/kombu/utils/imports.py", line 58, in symbol_by_name

celery-beat    |     reraise(ValueError,

celery-beat    |   File "/usr/local/lib/python3.8/site-packages/kombu/exceptions.py", line 21, in reraise

celery-beat    |     raise value.with_traceback(tb)

celery-beat    |   File "/usr/local/lib/python3.8/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name

celery-beat    |     module = imp(module_name, package=package, **kwargs)

celery-beat    |   File "/usr/local/lib/python3.8/site-packages/celery/utils/imports.py", line 100, in import_from_cwd

celery-beat    |     return imp(module, package=package)

celery-beat    |   File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module

celery-beat    |     return _bootstrap._gcd_import(name[level:], package, level)

celery-beat    |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

celery-beat    |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load

celery-beat    |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

celery-beat    |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

celery-beat    |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module

celery-beat    |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

celery-beat    |   File "/usr/src/app/apps/__init__.py", line 1, in <module>

celery-beat    |     from apps.celery import app as celery_app

celery-beat    |   File "/usr/src/app/apps/celery.py", line 5, in <module>

celery-beat    |     from configs.default.cron import task_schedule

celery-beat    |   File "/usr/src/app/configs/__init__.py", line 3, in <module>

celery-beat    |     from configs.default import *  # noqa

celery-beat    |   File "/usr/src/app/configs/default/__init__.py", line 9, in <module>

celery-beat    |     from .sites import *  # noqa isort:skip

celery-beat    |   File "/usr/src/app/configs/default/sites.py", line 30, in <module>

celery-beat    |     MIN_CHECKIN_TRAFFIC = int(os.getenv("MIN_CHECKIN_TRAFFIC", 10 * MB))

celery-beat    | ValueError: Couldn't import 'apps': invalid literal for int() with base 10: '10485760   # 10 * 1024 * 1024 (10MB)'

celery-beat    | 
```

**Comment by Ehco1996** [comment]
it's not a bug the log says: 
```
invalid literal for int() with base 10: '10485760
```
it means you `MIN_CHECKIN_TRAFFIC` is somthing wrong

**Comment by Alioth1017** [comment]
> it's not a bug the log says:
> 
> ```
> invalid literal for int() with base 10: '10485760
> ```
> 
> it means you is somthing wrong`MIN_CHECKIN_TRAFFIC`

Oh, it's my fault!
you are right, my env file is like this
```yaml
# 签到流量设置
MIN_CHECKIN_TRAFFIC = 10485760   # 10 * 1024 * 1024 (10MB)
```
and correct way of writing is
```yaml
MIN_CHECKIN_TRAFFIC = 10485760
# 10 * 1024 * 1024 (10MB)
```

Thanks ~
