### ISSUE TITLE
不好意思，第一次遇到这个问题，创建管理员账号报错。

### ISSUE THREAD

**Issue by cheapssr** [Ehco1996/django-sspanel#71]
前面的创建数据库和数据库的权限我检查过，没有问题，就是创建管理员账号时出错，第一次遇到。
有点蒙蔽，
[root@xxxxxx django-sspanel]# python manage.py createsuperuser
Username: adminxxxxxxxxx
Email address: xxxxxxx@xxx.com
Password:
Password (again):
Traceback (most recent call last):
  File "/www/wwwroot/www.xxxxxxxxx.xxx/django-sspanel/shadowsocks/models.py", line 99, in save
    ss_user = self.ss_user
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 389, in __get__
    self.related.get_accessor_name()
django.db.models.fields.related_descriptors.RelatedObjectDoesNotExist: User has no ss_user.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 59, in execute
    return super().execute(*args, **options)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 179, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
  File "/root/.pyenv/versions/venv-sspanel/lib/python3.6/site-packages/django/contrib/auth/models.py", line 161, in create_superuser

**Comment by Ehco1996** [comment]
代码升级到最新版本了么？ 
如果是的
把创建的时候的截图附上

**Comment by cheapssr** [comment]
是最新的版本，，我刚提issue，就升级了一次啊，
奥，我好像找到问题了，我一直是这样拉取的
git clone https://github.com/Ehco1996/django-sspanel.git
现在应该这样
git clone -b master https://github.com/Ehco1996/django-sspanel.git

我再试试去，不行再上截图
