### ISSUE TITLE
节点部署的时候运行server.py报错

### ISSUE THREAD

**Issue by startwish** [Ehco1996/django-sspanel#86]
报错的内容
IPv6 support
Traceback (most recent call last):
  File "server.py", line 73, in <module>
    main()
  File "server.py", line 55, in main
    if get_config().API_INTERFACE == 'ehcomod':
AttributeError: 'NoneType' object has no attribute 'API_INTERFACE'

**Comment by startwish** [comment]
重装了好几遍
现在又是这样的..
IPv6 support
2018-02-28 14:36:40 INFO     util.py:85 loading libcrypto from libcrypto.so.10
2018-02-28 14:36:40 INFO     asyncdns.py:324 dns server: [('108.61.10.10', 53)]
2018-02-28 14:36:40 INFO     shell.py:72 ShadowsocksR 3.4.0 2017-07-27
2018-02-28 14:36:40 INFO     web_transfer.py:429 current process RLIMIT_NOFILE resource: soft 1024000 hard 1024000
2018-02-28 14:36:40 ERROR    web_transfer.py:51 Traceback (most recent call last):
  File "/root/shadowsocksr/web_transfer.py", line 35, in getApi
    res = self.session_pool.get(url, params=payload, timeout=10)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /api/nodes/1?token=ZWhjbysyMzQ1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff9c0732d0>: Failed to establish a new connection: [Errno 111] Connection refused',))

2018-02-28 14:36:40 ERROR    web_transfer.py:457 Traceback (most recent call last):
  File "/root/shadowsocksr/web_transfer.py", line 439, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocksr/web_transfer.py", line 321, in pull_db_all_user
    nodeinfo = api.getApi('/nodes/{}'.format(node_id))
  File "/root/shadowsocksr/web_transfer.py", line 52, in getApi
    raise Exception('network issue or server error!')
Exception: network issue or server error!

2018-02-28 14:37:40 ERROR    web_transfer.py:51 Traceback (most recent call last):
  File "/root/shadowsocksr/web_transfer.py", line 35, in getApi
    res = self.session_pool.get(url, params=payload, timeout=10)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /api/nodes/1?token=ZWhjbysyMzQ1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7eff9c0dd910>: Failed to establish a new connection: [Errno 111] Connection refused',))

2018-02-28 14:37:40 ERROR    web_transfer.py:457 Traceback (most recent call last):
  File "/root/shadowsocksr/web_transfer.py", line 439, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocksr/web_transfer.py", line 321, in pull_db_all_user
    nodeinfo = api.getApi('/nodes/{}'.format(node_id))
  File "/root/shadowsocksr/web_transfer.py", line 52, in getApi
    raise Exception('network issue or server error!')
Exception: network issue or server error!

^CTraceback (most recent call last):
  File "server.py", line 66, in main
    thread.join(10.0)
  File "/usr/lib64/python2.7/threading.py", line 962, in join
    self.__block.wait(delay, balancing)
  File "/usr/lib64/python2.7/threading.py", line 362, in wait
    _sleep(delay)
KeyboardInterrupt

**Comment by startwish** [comment]
试了下，就是在装了面板的VPS上不能正常用，在其他的VPS上部署就正常

**Comment by Ehco1996** [comment]
https://github.com/Ehco1996/shadowsocksr
这里看教程
